PodShare/app/models/list.py
import sqlalchemy as sa
from sqlalchemy.orm import relationship
from app import db
from app.models.basemodel import BaseModel


class List(BaseModel, db.Model):
    owner_id = sa.Column(sa.String(60), sa.ForeignKey("user.id"), nullable=False)
    user_id = sa.Column(sa.String(60), sa.ForeignKey("user.id"), nullable=False)

    list_owner = relationship(
        "User", foreign_keys=[owner_id], back_populates="fav_user_list"
    )

PodShare/app/models/post.py
import sqlalchemy as sa
from sqlalchemy.orm import relationship
from app import db
from app.models.basemodel import BaseModel
from app.models.comment import Comment
from app.models.like import Like
from app.models.play import Play


class Post(BaseModel, db.Model):
    caption = sa.Column(sa.Text, nullable=False)
    user_id = sa.Column(sa.String(60), sa.ForeignKey("user.id"), nullable=False)
    likes = relationship("Like", backref="post")
    plays = relationship("Play", backref="post")
    audio = relationship("Audio", backref="post")
    comments = relationship("Comment", backref="post")

PodShare/app/controllers/post.py
import uuid
from flask import session, request, abort
from sqlalchemy import desc
from app import db
from app.models.audio import Audio
from app.models.post import Post
from app.models.like import Like
from app.models.play import Play
from app.models.comment import Comment
from app.utils.response import generate_response
from app.utils.constants import HTTP_201_CREATED, HTTP_200_OK


class PostController:
    def all_posts(self):
        posts = db.session.query(Post).all()
        return generate_response(
            data=[post.to_json() for post in posts], message="Posts"
        )

    def feed(self):
        posts = db.session.query(Post).order_by(desc(Post.created_at)).limit(10)
        # prevent repeated feed data -- to be implemented later
        if not session.get("viewed_posts"):
            session["viewed_posts"] = []
        for post in posts:
            session.get("viewed_posts").append(post.id)
        return posts

    def upload(self):
        form_audio = request.files.get("audio")
        form_caption = request.form.get("caption")
        audio_path = f'audio/{str(uuid.uuid4())}.{form_audio.filename.split(".")[1]}'
        post = Post(caption=form_caption, user_id=session.get("user").get("id"))
        db.session.add(post)
        db.session.commit()

        # get mimetype
        mime = ""
        if audio_path.split(".")[-1] == "mp3":
            mime = "audio/mp3"
        audio = Audio(url=audio_path, mime=mime, post_id=post.id)
        form_audio.save(audio_path)
        db.session.add(audio)
        db.session.commit()
        return generate_response(
            data=post.to_json(), message="Post Uploaded", status_code=HTTP_201_CREATED
        )

    def get_post(self, post_id):
        post = db.session.query(Post).filter_by(id=post_id).first()
        if not post:
            abort(404)
        like_count = db.session.query(Like).filter_by(post_id=post.id).count()
        play_count = db.session.query(Play).filter_by(post_id=post.id).count()
        comment_count = db.session.query(Comment).filter_by(post_id=post.id).count()
        post = post.to_json()
        post.update(
            {
                "like_count": like_count,
                "play_count": play_count,
                "comment_count": comment_count,
            }
        )
        return generate_response(data=post, message="Post")

    def get_post_details(self, post_id):
        post = self.get_post(post_id)[0]["data"]
        comments = db.session.query(Comment).filter_by(post_id=post["id"]).all()
        comments = [comment.to_json() for comment in comments]
        post["comments"] = comments
        return generate_response(data=post, message="post details")

PodShare/app/routes/auth.py
from flask import Blueprint, render_template, session, redirect, url_for
from app.controllers.user import UserAuthentication, UserController

auth_bp = Blueprint("auth", __name__)
auth_frontend_bp = Blueprint("auth_frontend", __name__)


@auth_bp.route("/login", methods=["POST"], strict_slashes=False)
def login():
    UserAuthentication().login()
    return redirect(url_for("home.index"))


@auth_bp.route("/register", methods=["POST"], strict_slashes=False)
def register():
    UserController().create_user()
    return redirect(url_for("auth_frontend.login"))


@auth_bp.route("/logout", strict_slashes=False)
def logout():
    return UserAuthentication().logout()


# frontend routes


@auth_frontend_bp.route("/register", strict_slashes=False)
def register():
    if session.get("user"):
        return redirect(url_for("home.index"))
    return render_template("register.html", title="Register")


@auth_frontend_bp.route("/login", strict_slashes=False)
def login():
    if session.get("user"):
        return redirect(url_for("home.index"))
    return render_template("login.html", title="Login")

PodShare/app/routes/home.py
from flask import Blueprint, render_template, session
from app.controllers.post import PostController

home_frontend_bp = Blueprint("home", __name__)


@home_frontend_bp.route("/home", strict_slashes=False)
def index():
    return render_template(
        "home.html",
        title="Home",
        user=session.get("user"),
        feed=PostController().feed(),
    )

PodShare/app/routes/list.py
from flask import Blueprint, render_template, session
from app.controllers.user import UserAuthentication

list_frontend_bp = Blueprint("list", __name__)


@list_frontend_bp.route("/list", strict_slashes=False)
@UserAuthentication().login_required
def index():
    return render_template("list.html", user=session.get("user"))

PodShare/app/routes/post.py
from flask import Blueprint, render_template
from app.controllers.post import PostController
from app.controllers.user import UserAuthentication

post_bp = Blueprint("post", __name__, url_prefix="/api/posts")
post_frontend_bp = Blueprint("post_frontend", __name__)


@post_bp.route("/", methods=["POST"], strict_slashes=False)
@UserAuthentication().login_required
def upload():
    return PostController().upload()


@post_bp.route("/<post_id>", strict_slashes=False)
def get_post(post_id):
    return PostController().get_post(post_id)


@post_bp.route("/", strict_slashes=False)
def all_posts():
    return PostController().all_posts()


@post_frontend_bp.route("/posts/<post_id>", strict_slashes=False)
def post_page(post_id):
    post = PostController().get_post_details(post_id)[0]["data"]
    return render_template("post.html", post=post)

PodShare/app/routes/profile.py
from time import sleep
from flask import Blueprint, redirect, render_template, url_for, session, Response
from app.controllers.user import UserAuthentication, UserController

profile_frontend_bp = Blueprint("profile", __name__)


@profile_frontend_bp.route("/<username>", strict_slashes=False)
def index(username):
    if username == "me":
        if not UserAuthentication().is_logged_in():
            return redirect(url_for("auth_frontend.login"))
        username = session.get("user").get("username")
    user = UserController().find_user(username)
    return render_template("profile.html", title=username, user=user)


@profile_frontend_bp.route("/test")
def test():
    return render_template("test.html")


@profile_frontend_bp.route("/audio")
def audio():
    def generate():
        with open("audio/mine.mp3", "rb") as f:
            data = f.read(1024)
            while data:
                yield data
                data = f.read(1024)

    return Response(generate(), mimetype="audio/mp3")

PodShare/app/templates/50x.html
{% extends 'base.html' %}

{% block title %}
500 Internal Error - 
{{ super() }}    
{% endblock title %}


{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/error.css') }}">
{% endblock %}

{% block navBar %}
{% endblock navBar %}

{% block content %}
<div class="error-container">
    <h1>500 Internal Error</h1>
</div>

{% endblock content %}

PodShare/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} - PodShare</title>
    <script src="{{ url_for('static', filename='scripts/jquery-3.7.1.min.js') }}"></script>
    {% block styles %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
    {% endblock styles %}
</head>
<body>
    <header>
        <h1 class="logo">PodShare</h1>
    </header>
    <article class="notification">Hello world</article>
{% block navBar %}
    <nav>
        <a href="{{ url_for('home.index') }}" class="link home">Home</a>
        <a href="{{ url_for('list.index') }}" class="link list">List</a>
        <a href="{{ url_for('profile.index', username='me') }}" class="link profile">Profile</a>
        <div></div>
        <div class="profile-card">
            {% if user %}
            <img src="{{ url_for('static', filename='assets/profile.png') }}" alt="Profile" class="profile-image">
                <div class="profile-names">
                    <p>{{ user.fullname }}</p>
                    <p>{{ user.username }}</p>
                </div>
                <div class="hover"><span class="fa fa-ellipsis-v"></span>
                <div class="logout-menu"><a href="{{ url_for('auth.logout') }}">Logout</a></div></div>
            {% else %}
                <div>
                    <h3><a href="{{ url_for('auth.login') }}">Login</a></h3>
                </div>
                {% endif %}
            <script>
                $(
                        $('.hover').hover(function() {
                            $('.logout-menu').toggleClass('show-menu')
                        })
                )
            </script>
        </div>
    </nav>
{% endblock %}
    {% block content %}
    {% endblock content %}
</body>
<script src="{{ url_for('static', filename='scripts/main.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/playback.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/like.js') }}"></script>
</html>

PodShare/app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Home 
{{ super() }}    
{% endblock title %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/post.css') }}">
    <script type="module" src="{{ url_for('static', filename='scripts/upload.js') }}" defer></script>
{% endblock %}

{% block content %}
    <main>
        <form method="post" class="new-post">
            <input type="text" name="caption" id="caption" class="caption" placeholder="Enter Audio Caption" required>
            <div>
                <input type="file" name="audio-file" id="audio-file" class="audio-file" accept=".mp3, .wav" placeholder="Upload" required>
                <input type="submit" class="post-button button" value="Post">
            </div>
        </form>
        <hr>
    {% if feed %}
        {% for post in feed %}
        <article class="post">
            <div class="post-text">
                <img src="{{ url_for('static', filename='assets/profile.png') }}" alt="Profile" class="profile-image">
                <div>
                    <p><span class="full-name">{{ post.user.fullname }}</span> <span>{{ post.user.username }}</span></p>
                    <p>{{ post.caption }}</p>
                </div>
            </div>
            <div class="controls">
                <button class="comments"><span class="fa fa-comment"></span></button>
                <button class="play" data-audio="{{post.id}}" onclick="action(this);"><span class="fa fa-play"><span style="padding: 2px;">{{ post.plays|length }}</span></span></button>
                <button class="like" data-post="{{ post.id }}"> <span class="fa fa-heart"><span style="padding: 2px;">{{ post.likes|length }}</span></span></button>
                <button class="share"> <span class="fa fa-share"></span></button>
            </div>
        </article>
        <hr>
        {% endfor %}
    {% else %}
        <article class="post post-text">You are up to date</article>
    {% endif %}
    </main>
{% endblock %}

PodShare/app/templates/index.html
{% extends 'base.html' %}

{% block navBar %}
    
{% endblock %}

{% block content %}
<center>
<br>
<br>
    Welcome to podshare
</center>

{% endblock content %}

PodShare/app/templates/list.html
{% extends 'base.html' %}

{% block title %}
{% if title %}
    {{ title }}
{% else %}
    List
{% endif %}
{{ super() }}    
{% endblock title %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/post.css') }}">
{% endblock %}

{% block content %}
    <main>
        <hr>
        <article class="post">
            <div class="post-text">
                <img src="{{ url_for('static', filename='assets/profile.png') }}" alt="Profile" class="profile-image">
                <div>
                    <p><span class="full-name">Emmanuel Nwafor</span> <span>emmo00</span></p>
                    <p>2 followers</p>
                    <p>4 posts</p>
                </div>
            </div>
        </article>
        <hr>
        <!--more-->
        <article class="post">
            <div class="post-text">
                <img src="{{ url_for('static', filename='assets/profile.png') }}" alt="Profile" class="profile-image">
                <div>
                    <p><span class="full-name">Emmanuel Nwafor</span> <span>emmo00</span></p>
                    <p>2 followers</p>
                    <p>4 posts</p>
                </div>
            </div>
        </article>
        <hr>
        <article class="post">
            <div class="post-text">
                <img src="{{ url_for('static', filename='assets/profile.png') }}" alt="Profile" class="profile-image">
                <div>
                    <p><span class="full-name">Emmanuel Nwafor</span> <span>emmo00</span></p>
                    <p>2 followers</p>
                    <p>4 posts</p>
                </div>
            </div>
        </article>
        <hr>
        <article class="post">
            <div class="post-text">
                <img src="{{ url_for('static', filename='assets/profile.png') }}" alt="Profile" class="profile-image">
                <div>
                    <p><span class="full-name">Emmanuel Nwafor</span> <span>emmo00</span></p>
                    <p>2 followers</p>
                    <p>4 posts</p>
                </div>
            </div>
        </article>
        <hr>
        <article class="post">
            <div class="post-text">
                <img src="{{ url_for('static', filename='assets/profile.png') }}" alt="Profile" class="profile-image">
                <div>
                    <p><span class="full-name">Emmanuel Nwafor</span> <span>emmo00</span></p>
                    <p>2 followers</p>
                    <p>4 posts</p>
                </div>
            </div>
        </article>
        <hr>
    </main>
{% endblock %}

PodShare/app/templates/login.html
{% extends 'register.html' %}

{% block title %}
{% if title %}
    {{ title }}
{% else %}
    Login
{% endif %}
{{ super() }}    
{% endblock title %}

{% block form %}
<form action="{{ url_for('auth.login') }}" method="post">
    <h3>Login</h3>
        {% if message %}
            <div class="alert"> {{ message }} </div>
        {% endif %}
    <input type="email" name="email" id="email" placeholder="Your email Address" required>
    <input type="password" name="password" id="password" placeholder="Enter Password" required>

    <input class="submit-button" type="submit" value="Login">
</form>
<br>
<br>
<br>
<button id="registerButton" class="register-button">Create a new account</button>

	<script>
		document.getElementById("registerButton").addEventListener("click", function() {

			window.location.href = "http://127.0.0.1:5000/register";
			});
	</script>
{% endblock %}

PodShare/app/templates/post.html
{% extends 'base.html' %}

{% block title %}
{% if title %}
    {{ title }}
{% else %}
    Post
{% endif %}
{{ super() }}
{% endblock title %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/post.css') }}">
{% endblock %}


{% block content %}
{{ post }}
<main>
    <article class="post">
        <div>{{ post.caption }}
    </div>
        
    </article>
    <article class="comments">
        {% for comment in post.comments %}
        {{comment.caption}}
        {% endfor %}
    </article>
</main>
{% endblock %}

PodShare/app/templates/profile.html
{% extends 'base.html' %}

{% block title %}
{% if title %}
    {{ title }}
{% else %}
    Profile
{% endif %}
{{ super() }}    
{% endblock title %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/post.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/profile.css') }}">
{% endblock %}

{% block content %}
    <main>
        <article class="profile-header">
            <img src="{{ url_for('static', filename='assets/profile.png') }}" alt="Profile" class="profile-image">
            <div>
                <p><span class="full-name">{{ user.fullname }}</span> <span>{{ user.username}}</span></p>
                <p>{{ user.bio }}</p>
                <div>
                    <div></div>
                    <p>{{ user.followers|length }} followers</p>
                </div>
            </div>
        </article>
        <hr>
        {% if user.posts %}
        {% for post in user.posts %}
        <article class="post">
            <div class="post-text">
                <img src="{{ url_for('static', filename='assets/profile.png') }}" alt="Profile" class="profile-image">
                <div>
                    <p><span class="full-name">{{ user.fullname }}</span> <span>{{ user.username }}</span></p>
                    <p>{{ post.caption }}</p>
                </div>
            </div>
            <div class="controls">
                <button class="comments"><span class="fa fa-comment"></span></button>
                <button class="play" data-audio="{{post.id}}" onclick="action(this);"><span class="fa fa-play"><span style="padding: 2px;">{{ post.plays|length }}</span></span></button>
                <button class="like" data-post="{{ post.id }}"> <span class="fa fa-heart"><span style="padding: 2px;">{{ post.likes|length }}</span></span></button>
                <button class="share"> <span class="fa fa-share"></span></button>
            </div>
        </article>
        <hr>
        {% endfor %}
        {% else %}
        <h2 class="post">No posts yet </h2>
        {% endif %}

    </main>
{% endblock %}

PodShare/app/templates/register.html
{% extends 'base.html' %}

{% block title %}
{% if title %}
    {{ title }}
{% else %}
    Register
{% endif %}
{{ super() }}    
{% endblock title %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/forms.css') }}">
{% endblock %}

{% block navBar %}

{% endblock navBar %}

{% block content %}

<main>
    <article class="hero">
        <h2 id="welcomeTitle">Welcome to PodShare <br> Share your voice.</h2>
        <br><br>
        <p id="welcomeMessage">A vibrant community where audio becomes a canvas for your creativity. Dive into a world where every sound
            carries a story, every note is a glimpse into someone's thoughts, and avery caption adds depth to the
            experience</p>
    </article>
    <article class="form" style="max-height: 100vh;">
        {% block form %}
        <form action="{{ url_for('auth.register') }}" method="post">
            <h3>Register</h3>

            {% if message %}
                <div class="alert"> {{ message }} </div>
            {% endif %}

            <input type="text" name="fullname" id="fullname" placeholder="Full Name" required>
            <input type="text" name="username" id="username" placeholder="Username" required>
            <input type="email" name="email" id="email" placeholder="Your email Address" required>
            <input type="password" name="password" id="password" placeholder="Pick a Password" required>
            <input type="password" name="confirm_password" id="confirm_password" placeholder="Confirm your Password" required>
            <input type="text" name="bio" id="bio" placeholder="Enter a little description about yourself" style="height:100px" required>
            <input class="submit-button" type="submit" value="Register">
        </form>
            
        {% endblock form %}
    </article>
</main>

{% endblock content %}

PodShare/app/templates/test.html
<!DOCTYPE html>
<html>
<head>
    <title>Audio Player</title>
</head>
<body>
    <audio id="audio-player" controls>
        <source src="" type="audio/mpeg">
    </audio>
    <button id="play-button">Play</button>
    <button id="pause-button">Pause</button>

    <script>
        // JavaScript code to control audio playback
        const audioPlayer = document.getElementById('audio-player');
        const playButton = document.getElementById('play-button');
        const pauseButton = document.getElementById('pause-button');

        playButton.addEventListener('click', async () => {
            await audioPlayer.play();
        });

        pauseButton.addEventListener('click', () => {
            audioPlayer.pause();
        });

        // Set the audio source to the Flask route that serves the audio file
        audioPlayer.src = '/audio';
    </script>
</body>
</html>